### ISSUE TITLE
can this run on a k8s cluster?

### ISSUE THREAD

**Issue by anuaimi** [relferreira/kubedev#49]
I'd prefer to run this on the cluster.  It would be great if there was instructions on how to deploy this.

**Comment by relferreira** [comment]
Hello @anuaimi, I've never deployed kubedev inside a cluster. I will investigate what I need to change to make this work.

**Comment by anuaimi** [comment]
I’m also willing to investigate. I think it may not be that big a task. I’ll post some thoughts once I’ve done some research

**Comment by relferreira** [comment]
Hello @anuaimi, I didn't forget this issue. I already know how to set the necessary credentials to run the `kubectl` commands inside a cluster, but I'm having problems with the front-end.

**Comment by relferreira** [comment]
Hello @anuaimi, I think I finally resolved this issue. Can you please try the solution?
